# Generated by Django 5.1.2 on 2024-10-15 18:59

import time
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='commentary',
            field=models.TextField(verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='last_datetime_sending',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Время рассылки'),
        ),
        migrations.AlterField(
            model_name='logs',
            name='status',
            field=models.CharField(blank=True, choices=[(True, 'Успешно'), (False, 'Неудача')], default=False, max_length=30, null=True, verbose_name='Попытка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='next_date',
            field=models.DateTimeField(default=time.localtime, verbose_name='Следующая рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=time.localtime, verbose_name='Начало рассылки'),
        ),
        migrations.AlterField(
            model_name='message',
            name='content',
            field=models.TextField(verbose_name='Содержание'),
        ),
        migrations.AlterField(
            model_name='message',
            name='topic',
            field=models.CharField(max_length=250, verbose_name='Тема'),
        ),
    ]
