# Generated by Django 5.1.2 on 2024-10-15 20:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0002_alter_client_commentary_alter_client_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='next_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Следующая рассылка'),
        ),
        migrations.AlterField(
            model_name='mailing',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Начало рассылки'),
        ),
    ]
