# Generated by Django 5.1.2 on 2024-10-19 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailing', '0004_client_owner_mailing_owner_message_owner_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mailing',
            options={'ordering': ('start_date',), 'permissions': [('can_edit_is_active_mailing', 'Can edit active mailing'), ('can_view_any_mailing', 'Can view any mailing')], 'verbose_name': 'рассылка', 'verbose_name_plural': 'рассылки'},
        ),
    ]
